on:
  issue_comment:
    types: [created]
  pull_request:
    branches:
      - master

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.BENCHMARKS_PROJECT_ID }}
          service_account_key: ${{ secrets.BENCHMARKS_SA_KEY }}
          export_default_credentials: true
      - run: make benchmarks BENCHMARK_OUTPUT=benchmarks.out
      - run: |
          jq -nc '{ "body": "$(cat benchmarks.out)" }' | \
          curl -sL -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.event.pull_request.statuses_url }}"
